blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/orgs/peers/discussions/categories/ideas-feature-requests
    about: Share your new ideas for features and enhancements in our discussions.

  - name: â“ Question Request
    url: https://discord.gg/
    about: Get faster answers to your questions by joining us on Discord!
